# Generated by Django 4.0.3 on 2022-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование кейса')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Изображение')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='Содержание кейса')),
                ('slug', models.SlugField(unique=True, verbose_name='Наименование кейса')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
    ]
